[package]
name = "nucleo-rust"
version = "0.2.0"
authors = ["kflange <zknsftk1msrk@gmail.com>"]
edition = "2018"

keywords = [
  "arm",
  "embedded",
  "mbed",
  "cortex-m",
  "stm32f401",
]

[dependencies]
cortex-m-rt = "0.6.8"
cortex-m = "0.6.0"
panic-halt = "0.2.0"
cortex-m-semihosting = "0.3.2"


[dependencies.stm32f4xx-hal]
version = "0.3.0"
features = ["stm32f401", "rt"]

[profile.dev]
debug = true
lto = true

[profile.release]
debug = true
lto = true
