[package]
name = "nucle-rust"
version = "0.1.0"
authors = ["kflange <zknsftk1msrk@gmail.com>"]

[dependencies]
cortex-m-rt = "0.5.2"
panic-semihosting = "0.3.0"
cortex-m-semihosting = "0.3.0"

[profile.dev]
incremental = false
codegen-units = 1

[profile.release]
codegen-units = 1
debug = false
lto = true
