[package]
name = "nucle-rust"
version = "0.1.0"
authors = ["kflange <zknsftk1msrk@gmail.com>"]

[dependencies]
cortex-m-rt = "0.5.3"
panic-semihosting = "0.3.0"
cortex-m-semihosting = "0.3.1"
stm32f401re_hal = { path = "./stm32f401re_hal" }
cortex-m = "0.5.6"

[profile.dev]
incremental = false
# codegen-units = 1
debug = true
lto = true

[profile.release]
incremental = false
# codegen-units = 1
debug = false
lto = true
